---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,message = FALSE,error = FALSE,warning = FALSE,
  comment = "#>"
)
```

# Projeto Mestrado Rodrigo Perim

## Carregando Pacotes

```{r}
library(tidyverse)
library(ncdf4)
library(geobr)
```

## Ler um arquivo de dados `.NC`

```{r}
# Buscar os nomes dos arquivo .nc4
list_nc4 <- list.files("data-raw/",
           recursive = TRUE,full.names = TRUE,pattern = ".nc4")

# Abrindo o1 arquivo
nc_obj <- nc_open(list_nc4[1])

# buscando os nomes dos atributos no arquivo
# names(nc_obj[['var']])
```

## Função para ler um arquivo e extrair colunas de interesse

```{r}
## função para ler arquivos NCD4
ncdf_reader <- function(file_path){
  nc_file <- ncdf4::nc_open(file_path)
  df <- data.frame(
    "longitude"=ncdf4::ncvar_get(nc_file,varid="longitude"),
    "latitude"=ncdf4::ncvar_get(nc_file,varid="latitude"),
    "time"=ncdf4::ncvar_get(nc_file,varid="time"),
    "xco2"=ncdf4::ncvar_get(nc_file,varid="xco2"),
    "xco2_quality_flag"=ncdf4::ncvar_get(nc_file,varid="xco2_quality_flag"),
    "xco2_incerteza"=ncdf4::ncvar_get(nc_file,varid="xco2_uncertainty"),
    "fs"=ncdf4::ncvar_get(nc_file,varid="Retrieval/fs"),
    "fs_rel"=ncdf4::ncvar_get(nc_file,varid="Retrieval/fs_rel"),
    "path" = file_path
  )
  ncdf4::nc_close(nc_file)
  return(df)
}
```

## Vamos ler todos os arquivos na pasta
```{r}
# Usando a função map do dplyr
data_set <- map_df(list_nc4,ncdf_reader)
```

## Resumo dos dados
```{r}
data_set <- data_set |> 
  mutate(
   time_1 = lubridate::as_datetime(time, tz = "America/Sao_Paulo"),
   time = lubridate::date(time),
  )
glimpse(data_set)
```

## Retirando 500 obs do banco de dados e plotando

```{r}
data_set |> 
  sample_n(500) |> 
  ggplot(aes(x=longitude, y=latitude)) +
  geom_point()
```

## Então vamos plotar dentro do mapa do Brasil

```{r}
## Pegando o contorno do BR
br <- read_country(showProgress = FALSE)
```
fazer o plot do BR

```{r}
br |>
  ggplot2::ggplot() +
  ggplot2::geom_sf(fill="white", color="#FEBF57",
                   size=.15, show.legend = FALSE)
```

```{r}
br |>
  ggplot() +
  geom_sf(fill="white", color="#FEBF57",
          size=.15, show.legend = FALSE) +
  geom_point(data= data_set |> 
               sample_n(10500) ,
             aes(x=longitude, y=latitude),
             shape=3,
             col="red",
             alpha=0.2)
```
















